// Mocks generated by Mockito 5.0.5 from annotations
// in moody/test/user_bloc_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:moody/data/models/user.dart' as _i2;
import 'package:moody/data/repositories/user_repository.dart' as _i3;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeUser extends _i1.Fake implements _i2.User {}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.User get() =>
      (super.noSuchMethod(Invocation.method(#get, []), returnValue: _FakeUser())
          as _i2.User);
  @override
  void add(_i2.User? user) =>
      super.noSuchMethod(Invocation.method(#add, [user]),
          returnValueForMissingStub: null);
  @override
  void update(_i2.User? user) =>
      super.noSuchMethod(Invocation.method(#update, [user]),
          returnValueForMissingStub: null);
  @override
  void delete(_i2.User? user) =>
      super.noSuchMethod(Invocation.method(#delete, [user]),
          returnValueForMissingStub: null);
}
